IPR_site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^polls/',include('polls.urls', namespace='polls')),
    url(r'^nested_admin/',include('nested_admin.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

polls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<survey_id>\d+)/respond/$',views.respond,name='respond'),
	url(r'^(?P<response_id>\d+)/results/$',views.booya,name='booya'),
)

polls/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError
import re, json
from polls import eqparser #This should not be in the app.
import sympy

#from django.utils.translation import ugettext_lazy as _
#I18n later.
def _(text):
    return text

class Survey(models.Model):
    title = models.CharField(max_length=200)
    evaluator = models.CharField(max_length=200,blank=True,help_text=_("Leave this blank for the first save. Enter values such as .5{1}+.5{2} for two equally weighted questions."))
    def __str__(self):
        return self.title

class Response(models.Model):
    
    #Build this into a pseudo-JSON thing.
    survey = models.ForeignKey(Survey)
    #This means you have to write a separate view to edit the response.
    response_text = models.TextField()
    
    @property
    def response(self):
        return json.loads(self.response_text)

    def get_response_to_question(self,question):
        response = json.loads(self.response_text)
        return response['qpk'+question]

    def evalute(self):
        equation = eqparser.parse_equation(self.survey.evaluator)
        responses = self.response.items()
        return evaluate_equation(equation,responses.items())


#This may need subclassing.
class Question(models.Model):
    qtypes = (('CH',_('Multiple choice')),
              ('TE',_('Text')),
			  ('LT',_('Long text')),
              ('TF',_('True or false')),
                )
    survey = models.ForeignKey(Survey,blank=True,null=True)
    question = models.CharField(max_length=200)
    question_type = models.CharField(max_length=2,choices=qtypes)
    
    #This is all to show the PK on the list_display. May not be necessary.
    def primary_key(self):
        return self.pk

    primary_key = property(primary_key)

    @property
    def choices(self):
        return self.choice_set.all()
    @property
    def choice_tuple(self):
        return ((c.choice_value,c.choice_text) for c in self.choices)
    @property
    def choices_values(self):
        return (c.choice_value for c in self.choices)

    @property
    def choices_text(self):
        return (c.choice_text for c in self.choices)

    def clean(self):
        #Ripe for testing m'lad
        if self.question_type == "TF":
            if len(self.choices)>2:
                raise ValidationError(_("True/false questions must have only two options, True and False."))
            if not all([a=="True" or "False" for a in self.choices_values]):
                raise ValidationError(_("True/false questions must have only two options, True and False."))

    def __str__(self):  # Python 3: def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    choice_value = models.CharField(max_length=20,blank=True)
    def __str__(self):  # Python 3: def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from polls.models import Survey, Question, Choice
#For the renderer
from django.utils.safestring import mark_safe

#Shamelessly grabbed from HighLife, http://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms
class HorizontalRadioRenderer(forms.RadioSelect.renderer):
  def render(self):
    return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class ResponseForm(forms.Form):
    
    def __init__(self,survey,*args,**kwargs):
        super(ResponseForm,self).__init__(*args,**kwargs)
        #Expects survey
        self.survey = survey
        for question in self.survey.question_set.all():
            qchoices = question.choice_tuple
            if question.question_type == "CH":
                self.fields['qpk{}'.format(question.pk)]=forms.ChoiceField(label=question.question,choices=qchoices,widget=forms.RadioSelect(renderer=HorizontalRadioRenderer))
            if question.question_type == "TE":
                self.fields['qpk{}'.format(question.pk)] = forms.CharField(label=question.question)
            if question.question_type == "TF":
                self.fields['qpk{}'.format(question.pk)] = forms.ChoiceField(label=question.question, choices=qchoices, widget = forms.RadioSelect(renderer=HorizontalRadioRenderer))
            if question.question_type == "LT":
                self.fields['qpk{}'.format(question.pk)] = forms.CharField(label=question.question,widget=forms.Textarea)

polls/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Choice, Question, Survey, Response
from .forms import *

import json

def booya(request,response_id):
	#Delete almost immediately.
	context = {'response':get_object_or_404(Response,pk=response_id)}
	return render(request,'polls/booya.html',context)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        return Survey.objects.all()[:5]


class DetailView(generic.DetailView):
    model = Survey
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def respond(request,survey_id):
    #You goofed this, you need to create a JSON array such that you have { "response":{ "question_pk":question_pk, "answer": answer },{ "question_pk":question_pk, "answer":answer } ... }
	survey = get_object_or_404(Survey,pk=survey_id)
	if request.method == 'POST':
		form = ResponseForm(survey,request.POST)
		if form.is_valid():
		    #Create list of dictionaries
			r_raw = [ {'question':qpk, 'answer':answer } for qpk,answer in list( form.cleaned_data.items() ) ]
			r_text = json.dumps(r_raw)
			response = Response(survey=survey,response_text=r_text)
			response.save()
			return HttpResponseRedirect(reverse('polls:booya',kwargs={'response_id':response.pk}))
	else:
		form = ResponseForm(survey)
	context = { 'survey':survey, 'form':form }
	#Pass on this lad, look it up.
	return render(request,'polls/respond.html',context)

class Respond(generic.CreateView):
    model = Survey
    form_class = ResponseForm
    success_url = 'success/' #replace with url.reverse
    template_name = 'polls/create.html'

    def get(self,request,*args,**kwargs):
        # Does GET requests, returns blank formsets.
        self.object = None
        #Returns SurveyForm
        form_class = self.get_form_class()
        #Creates original form?
        form = self.get_form(form_class)
        return self.render_to_response(self.get_context_data(form=form))

    def post(self,request,*args,**kwargs):
        pass

    def form_valid(self,form,poll_form):
        pass

    def form_invalid(self,form,poll_form):
        pass

def vote(request, poll_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/base.html
{% extends "base.html" %}
{% block content %}
{% block polls_content %}
{% endblock %}
{% endblock %}

polls/templates/polls/booya.html
{% extends 'polls/base.html' %}
{% block polls_content %}
<h1>Results</h1>
<p>Developer note: Change qpk<var>x</var> to the question text. For example, turn "{% with response.response|first as first %}{{first.question}}{% endwith %}" into "{{response.survey.question_set.first}}". The important thing is we have the question ID, the 'score', then we can evaluate it and put the data into a graph.</p>
{% for question in response.response %}
<p>{{ question.question }}:{{ question.answer }}</p>
{% endfor %}
{% endblock %}

polls/templates/polls/create.html
{% extends "polls/base.html" %}
{% block polls_content %}
<h1>{{survey.title}}</h1>
<form action="{% url 'polls:respond' survey.id %}" method="post" onsubmit="return false();">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block polls_content %}

<h1>{{ survey.title }}</h1>
<form>
{% for poll in survey.poll_set.all %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<h2>{{ poll.question }}</h2>
{% for choice in poll.choice_set.all %}
	<input type="radio" name="q{{question.id}}choice" id="q{{question.id}}choice{{forloop.counter}}">{{choice.choice_text}}
{% endfor %}
{% endfor %}
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block polls_content %}
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
		<li><a href="{% url 'polls:respond' poll.id %}">{{ poll.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/respond.html
{% extends "polls/base.html" %}
{% block polls_content %}
{% include "polls/respond_base.html" with survey=survey %}
{% endblock %}

polls/templates/polls/respond_base.html
<h1>{{survey.title}}</h1>
<form action="{% url 'polls:respond' survey.id %}" method="post" onsubmit="return false();">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block polls_content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
{% endblock %}